version: "3"
services:
  linkazar:
    image: linkazar
    hostname: localhost
    ports: 
      - 8080:8080
    privileged: true

  redis:
    image: redis
    ports:
      - 6379:6379
    privileged: true

  mongo:
    image: mongo:4.4.6
    ports:
      - 27017:27017
    privileged: true

  cassandra:
    image: "cassandra:3.11.9"
    ports:
      - "9042:9042"
    environment:
      - "MAX_HEAP_SIZE=256M"
      - "HEAP_NEWSIZE=128M"